---
settings:
  name: BlueXP tiering
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP Tiering-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu BlueXP Tiering
      url: "/concept-cloud-tiering.html"
    - title: Verlagern Sie lokale Daten in die Cloud
      entries:
      - title: Tiering zu Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Tiering zu Azure Blob Storage
        url: "/task-tiering-onprem-azure.html"
      - title: Tiering zu Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Tiering zu StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Tiering zu S3 Objekt-Storage
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Lizenzierung einrichten
      url: "/task-licensing-cloud-tiering.html"
    - title: Häufig gestellte Fragen
      url: "/faq-cloud-tiering.html"
  - title: Einsatz von BlueXP Tiering
    entries:
    - title: Managen Sie Daten-Tiering
      url: "/task-managing-tiering.html"
    - title: Objekt-Storage managen
      url: "/task-managing-object-storage.html"
    - title: Testen Sie die Cloud-Performance
      url: "/task-tiering-test.html"
    - title: Tiering Übersicht für alle Cluster anzeigen
      url: "/task-tiering-onprem-overview.html"
    - title: Überwachen Sie den Status von Tiering-Warnmeldungen
      url: "/task-monitor-tiering-alerts.html"
  - title: Referenz
    entries:
    - title: Unterstützte Amazon S3-Storage-Klassen und Regionen
      url: "/reference-aws-support.html"
    - title: Unterstützte Azure-Zugriffsebenen und -Regionen
      url: "/reference-azure-support.html"
    - title: Unterstützte Google Cloud-Storage-Klassen und Regionen
      url: "/reference-google-support.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
