---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: BlueXP Tiering unterstützt zwei Zugriffs-Tiers und die meisten Regionen. 
---
= Unterstützte Azure Blob-Zugriffsebenen und Regionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Tiering unterstützt zwei Zugriffs-Tiers und die meisten Regionen.



== Unterstützte Azure Blob-Zugriffsebenen

Wenn Sie aus Ihren lokalen ONTAP Systemen ein Daten-Tiering auf Azure einrichten, verwendet BlueXP Tiering für Ihre inaktiven Daten automatisch die Hot-Access-Tier. BlueXP Tiering kann eine Lebenszyklusregel anwenden, sodass die Daten nach einer bestimmten Anzahl von Tagen von der _Hot_ Zugriffs-Tier auf die _Cool_ Zugriffs-Tier verschoben werden.

Wenn Sie die Zugriffsebene _Cool_ nicht wählen, verbleiben die Daten in der Zugriffsebene _Hot_ und es werden keine Regeln angewendet.

Wenn Sie eine Tiering-Lebenszyklusregel für BlueXP konfigurieren, dürfen Sie beim Einrichten des Containers in Ihrem Azure-Konto keine Lebenszyklusregeln konfigurieren.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Erfahren Sie mehr über Azure Blob Zugriffsebenen"^].



== Unterstützte Azure Regionen

BlueXP  Tiering unterstützt folgende Azure Regionen. Azure China Regionen werden nicht als Tiering-Ziele unterstützt.



=== Afrika

* Südafrika, Norden




=== Asien/Pazifik

* Australien Ost
* Australien Südosten
* Ostasien
* Japan Ost
* Japan West
* Korea Central
* Korea Süd
* Südostasien




=== Europa

* Frankreich, Mitte
* Deutschland West Central
* Deutschland, Norden
* Nordeuropa
* Großbritannien Süd
* UK West
* Westeuropa




=== Nordamerika

* Kanada Mitte
* Kanada Ost
* Zentral USA
* Osten US
* Osten US 2
* North Central USA
* South Central USA
* Westen USA
* USA, Westen 2
* West Central USA




=== Südamerika

* Brasilien Süd

