---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: BlueXP Tiering unterstützt mehrere Google Cloud Storage-Klassen und die meisten Regionen. 
---
= Unterstützte Google Cloud-Storage-Klassen und Regionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Tiering unterstützt mehrere Google Cloud Storage-Klassen und die meisten Regionen.



== Unterstützte GCP-Storage-Klassen

Wenn Sie das Daten-Tiering auf GCP einrichten, verwendet BlueXP Tiering für Ihre inaktiven Daten automatisch die Storage-Klasse _Standard_. BlueXP Tiering kann eine Lebenszyklusregel anwenden, sodass Daten nach einer bestimmten Anzahl von Tagen von der _Standard_ Storage-Klasse zu anderen Storage-Klassen überführt werden. Sie können aus folgenden Speicherklassen wählen:

* Nearline
* Coldline
* Archivierung


Wenn Sie keine andere Storage-Klasse wählen, verbleiben die Daten in der Storage-Klasse _Standard_, und es werden keine Regeln angewendet.

Wenn Sie eine Tiering-Lebenszyklusregel für BlueXP konfigurieren, dürfen Sie beim Einrichten des Buckets in Ihrem Google-Konto keine Lebenszyklusregeln konfigurieren.

https://cloud.google.com/storage/docs/storage-classes["Weitere Informationen zu Google Cloud Storage Classes"^].



== Unterstützte Google Cloud Regionen

BlueXP Tiering unterstützt folgende Regionen.



=== Nord- Und Südamerika

* Iowa
* Los Angeles
* Montreal
* N. Virginia
* Oregon –
* Sao Paulo, Brasilien
* South Carolina




=== Asien/Pazifik

* Hongkong
* Mumbai
* Osaka
* Singapur
* Sydney
* Taiwan
* Tokio




=== Europa

* Belgien
* Finnland
* Frankfurt
* London
* Niederlande
* Zürich

