---
sidebar: sidebar 
permalink: reference-aws-support.html 
keywords: aws, amazon, s3, support, regions, storage classes 
summary: BlueXP Tiering unterstützt mehrere S3 Storage-Klassen und die meisten Regionen. 
---
= Unterstützte S3-Storage-Klassen und Regionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Tiering unterstützt mehrere S3 Storage-Klassen und die meisten Regionen.



== Unterstützte S3-Storage-Klassen

Wenn Sie das Daten-Tiering auf AWS einrichten, verwendet BlueXP Tiering für Ihre inaktiven Daten automatisch die Storage-Klasse _Standard_. BlueXP Tiering kann eine Lebenszyklusregel anwenden, sodass Daten nach einer bestimmten Anzahl von Tagen von der _Standard_ Storage-Klasse zu einer anderen Storage-Klasse überführt werden. Sie können aus folgenden Speicherklassen wählen:

* Standard-infrequent Access (S3 Standard-IA)
* One Zone-infrequent Access (S3 One Zone-IA)
* Intelligentes Tiering (S3 Intelligent Tiering)
* Glacier Instant Retrieval


Wenn Sie keine andere Storage-Klasse wählen, verbleiben die Daten in der Storage-Klasse _Standard_, und es werden keine Regeln angewendet.

Wenn Sie eine Tiering-Lebenszyklusregel für BlueXP konfigurieren, dürfen Sie beim Einrichten des Buckets in Ihrem AWS-Konto keine Lebenszyklusregeln konfigurieren.

https://aws.amazon.com/s3/storage-classes/["Erfahren Sie mehr über S3-Storage-Klassen"^].



== Unterstützte AWS-Regionen

BlueXP Tiering unterstützt folgende AWS Regionen.



=== Asien/Pazifik

* Mumbai
* Seoul
* Singapur
* Sydney
* Tokio




=== Europa

* Frankfurt
* Irland
* London
* Paris
* Stockholm




=== Nordamerika

* Kanada Mitte
* US-Osten (N. Virginia)
* US-Osten (Ohio)
* US West (N. Kalifornien)
* US West (Oregon)




=== Südamerika

* São Paulo

